# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "dm-snapshot"
    "tcp_bbr"
    "sch_cake"
  ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 100;
    "kernel.core_pattern" = "|/bin/false";
    "net.ipv4.tcp_fastopen" = 3;
    "net.core.default_qdisc" = "cake";
    "net.ipv4.tcp_congestion_control" = "bbr";
    "net.ipv4.tcp_mtu_probing" = 1;
  };
  boot.kernelParams = [
    "amd_pstate=active"
    "zswap.enabled=1" # enables zswap
    "zswap.compressor=lz4" # compression algorithm
    "zswap.max_pool_percent=30" # maximum percentage of RAM that zswap is allowed to use
    "zswap.shrinker_enabled=1" # whether to shrink the pool proactively on high memory pressure
    "transparent_hugepage=madvise"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ffb7c1c3-8f4c-4a08-a077-5f5bcc4000bf";
    fsType = "ext4";
    options = [
      "discard"
      "noatime"
      "nodiratime"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b3c535a1-40bd-4fcc-9d83-e92a62a3e372";
    fsType = "ext4";
    options = [
      "discard"
      "noatime"
      "nodiratime"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/41fefdac-c7a1-429f-8ee9-76d29f0c61ed";
      options = [ "discard" ];
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  specialisation = {
    nvidia.configuration = {
      system.nixos.tags = [ "nvidia" ];
      services.xserver.videoDrivers = [ "nvidia" ];
      hardware = {
        nvidia = {
          open = false;
          package = config.boot.kernelPackages.nvidiaPackages.latest;
          prime = {
            offload = {
              enable = true;
              enableOffloadCmd = false;
            };
            amdgpuBusId = "PCI:0:5:0";
            nvidiaBusId = "PCI:0:1:0";
          };
        };
      };
    };
  };

  powerManagement = {
    powertop.enable = false;
  };

  hardware = {
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        ocl-icd
        libva-vdpau-driver
        libvdpau-va-gl
      ];
    };
    bluetooth = {
      enable = true; # enables support for Bluetooth
      powerOnBoot = true; # powers up the default Bluetooth controller on boot
      settings = {
        General = {
          Enable = "Source,Sink,Media,Socket";
          Experimental = true;
        };
      };
    };
  };
}
