icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
separator = "|"
separator_fg = "#ffffff"
separator_bg = "#000000"

[icons]
icons = "awesome6"

# [[block]]
# format="$icon{ $message|}"
# block = "pomodoro"
# notify_cmd = "notify-send '{msg}'"
# blocking_cmd = false

[[block]]
block = "amd_gpu"
device = "card2"
format = "AMD $icon $utilization $vram_used"
interval = 20

# [[block]]
# block = "nvidia_gpu"
# interval = 20
# gpu_id = 0
# format = "NVIDIA { $icon $utilization $temperature $clocks |}"

[[block]]
block = "uptime"
format = "$icon $text"
interval = 300

[[block]]
interval = 20
block = "cpu"
format = "$icon $barchart $utilization" 

[[block]]
block = "disk_space"
path = "/home/"
info_type = "available"
alert_unit = "GB"
interval = 3600 
warning = 20.0
alert = 10.0
format = "/home $icon $available"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 3600 
warning = 20.0
alert = 10.0
format = "/$icon $available"

[[block]]
interval = 20
block = "memory"
format = "$icon $mem_free"
format_alt = "$icon_swap $swap_used_percents.eng(w:2)"

[[block]]
interval = 20
block = "battery"
driver = "sysfs"
format = "$power $percentage{ $time|}"
full_format = "$icon $power $percentage{ $time|}"
empty_format = "$icon $power $percentage{ $time|}"
missing_format = "$icon $power $percentage{ $time|}"
charging_format = "$icon $power $percentage{ $time|}"
not_charging_format = "$icon $percentage{ $time|}"
 
# [[block]]
# block = "custom"
# command = "bash ~/.config/i3status-rust/power_mode.sh"
# json = true
# interval = 20

[[block]]
block = "bluetooth"
mac = "40:72:18:BD:17:14"
format = "$icon {$percentage |}"
disconnected_format = "$icon"
[block.battery_state]
"0..20" = "critical"
"21..65" = "warning"
"66..100" = "good"

[[block]]
block = "time"
interval = 10
format = "$timestamp.datetime(f:'%a %d.%m %H:%M:%S')"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
